baseURL = 'https://knikolaev.me'
defaultContentLanguage = 'en'
languageCode = 'en-us'
title = "Kirill Nikolaev"
theme = 'gokarna'

enableRobotsTXT = true

[menu]
	[[menu.main]]
	identifier = 'projects'
	url = '/projects/'
	name = 'Projects'
	weight = 1


	[[menu.main]]
	identifier = 'github'
	url = "https://github.com/knikolaeff"
	weight = 2
	pre = "<span data-feather='github'></span>"

	[[menu.main]]
	identifier = 'linkedin'
	url = "https://www.linkedin.com/in/kirill-nikolaev-ab4593242/"
	weight = 3
	pre = "<span data-feather='linkedin'></span>"

[params]
	description = 'Programming and FOSS enthusiast.'
	avatarURL = "images/photo_2023-01-10_16-22-09.jpg"
