baseurl = "https://knikolaev.me/"
title = "Kirill's Website"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "knikolaeff"

[markup.highlight]
style = "github-dark"

[params]
  author = "Kirill Nikolaev"
  info = "Programming and FOSS enthusiast. Open to work."
  description = "Kirill Nikolaev's personal website"
  keywords = "blog,developer,personal,nikolaev"
  avatarurl = "/photo.jpg"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/knikolaeff/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/kirill-nikolaev-ab4593242/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url  = "about"
[[menu.main]]
  name = "Projects"
  weight = 2
  url = "projects/"
[[menu.main]]
  name = "Support me"
  weight = 3
  url = "donate/"